#!/bin/bash
# Template from buildben copied to <my_project>/.envrc
# !! This script is executes EVERY TIME you enter the directory !!

# === Environment Variables ===========================================
### direnv changes into directory of .envrc and runs subshell, so $PWD is always project root.
export PROJECT_NAME=$(basename "$PWD")
export PROJECT_ROOT=$PWD
echo "Project name: $PROJECT_NAME"

# > hard-fail if someone runs pip outside the venv
export PIP_REQUIRE_VIRTUALENV=1

# > Uncomment to pin tool versions
# export PIPX_HOME=$PWD/.build-tools

# === direnv / venv ===================================================

#?? This is a direnv auto function. We don't use it
layout python3 # > create & activate .venv under .direnv/

# === Install pip-tools ===============================================

python -m pip show pip-tools >/dev/null 2>&1 || (
    echo "Installing pip-tools!" &&
        python -m pip install --quiet "pip-tools>=7.4"
)
