@startuml
left to right direction
' top to bottom direction

' === Global look & feel =============
skinparam defaultFontSize 20
skinparam BackgroundColor #99999910
skinparam package {
    BackgroundColor #99999999
    BorderColor #99999999
    BorderWidth 2
    FontColor   #ffffff
}
skinparam class {
    BackgroundColor #999999
    BorderColor     #00000099
}


' =====================================================================


' === Package: Global Environment =============
package "Global Environment" as GE {
    
    interface "buildben"      as B   <<CLI>>{
        +init-proj()
        +init-experiment()
    }
    class "pip / pipx"    as PIP <<CLI>>{
        +install()
    }
    
    class "just"          as J   <<CLI>>
    class "Direnv"        as D   <<CLI>>{
        +layout()
        +direnv reload()
        +direnv exec()
    }
    
}

' === Package: Project Directory =============
package "Project Directory" as PDIR {
    
    class "pyproject.toml"                          as PPRT <<File>>
    
    interface "justfile"                                as JF  <<File>> {
        +reset()
        +install-deps()
        +...()
    }
    
    class ".envrc"                                  as ERC  <<Config>>{
        +PROJECT_NAME
        +ENV_VARS
    }
    
    class "requirements.txt \n+ dev_requirements.txt" as RE   <<File>>
}

' === Package: Virtual Environment =============
package "Virtual Environment" as VENV {
    class "pip-tools"               as PT  <<Tool>>{
        +pip-compile()
        +pip-sync()
    }
    class "python dependencies"     as PD  <<Pkg>>
    ' VE o-- PD : contains
}


' ============================================================

' === Straight Arrows =============

<style>
arrow {
    LineColor #6da0d0
    FontColor #6da0d0
    LineThickness 2.5
    
    ' !! Not Working
    .test {
        LineColor #b35e5e
    }
}
</style>

' PT --> PD <<test>> : installs 
PT --> PD : installs
PIP --> B : installs 
B --> PDIR   : creates scaffold
ERC --> PT     : installs 
PT  --> RE     : compiles \n& syncs


' === SPecial Straight Arrows =============
<style>
arrow {
    LineColor #6dd089
    FontColor #6dd089

}
</style>

ERC --> VENV     : creates \n& activates
JF --> VENV : manages


' === Dependencies =============

<style>
arrow {
    LineStyle 10-5
    LineColor #0e467bee
    FontColor #0e467bee
}
</style>


D   <-- ERC 
J   <-- JF     
D   <-- JF     

JF  --> PT     
PT --> PPRT

' ERC -left-  JF     : interacts
' PPRT ..> PT    : read by
@enduml