---
config:
    title: build-ben runtime helpers
    theme: base
    themeVariables:
        fontSize: 20px
        
        # Nodes
        primaryTextColor: "#000000"      # Black
        primaryColor: "#999999"          # Grey
        primaryBorderColor: "#00000099"  # Black transparent
        
        # Links
        lineColor: "#0e467bee"        # Dark Blue transparent
        secondaryColor: "#0e467b03"   # Dark Blue transparent
        
        # Subgraphs
        tertiaryTextColor: "#ffffff"  # White
        tertiaryColor: "#99999999"    # Grey transparent
        tertiaryBorderColor: "#00000000" # Fully transparent
---



classDiagram
    %% ───────────────────────────  Classes  ───────────────────────────
    
    subgraph globalenvironment
        class buildben{
            +templates for justfile, .dot_envrc, 
            +init-project()
            +init-experiment()
            ...
            }

        class direnv{
            +layout python()
            +exec()
        }

        class pip_or_pipx{
            +install()
        }

        class just{
            +recipes()
            +variables()
        }
    
    end
    
        
    namespace virtual_environment{
        class pip-tools{
            +pip-compile()
            +pip-sync()
        }

        class python_dependencies{
        }
        
    }
    
    namespace project_directory{
        class venv{
        }
        class justfile{
            +reset-venv()
            +install-deps()
        }
        
        class dot_envrc{
        }
        
        class requirements_txt{
        }
        
    }
    


    %% ─────────────────────────── Relationships ───────────────────────
    
    %% ## Connections
    %% > Inheritance: "is-a", Empty arrow: <|--, Points towards the parent
    %% > Composition: "part-of", Filled diamond: --*, Points towards the whole
    %% > Aggregation: "used-by", Open diamond: --o, Points towards the user
    %% > Dependency: "depends-on", Dotted line: ..>, Points from the dependent to the supplier (supplier=dependency)
    
    %% BuildBen uses each helper
    %% pip_or_pipx <.. buildben : "installed by"
    %% pip_or_pipx <.. buildben : "installed by"
    %% buildben ..> direnv : 
    dot_envrc <.. venv : "auto-creates and activates"
    %% buildben ..> just : 
    %% buildben ..> pip-tools : 
    
    
    %% dot_envrc ..> direnv
    %% venv o-- pip-tools
    

    %% just ..> direnv : "recipes call direnv exec"
    %% just <.. justfile
    %% justfile ..> direnv
    %% justfile ..> pip-tools

    
    %% requirements_txt ..> justfile : created by


    %% relationships
    buildben ..> direnv
    buildben ..> just
    pip_or_pipx  ..> buildben : "installed by"

    %% direnv ..> virtual_environment.Venv : "creates/activates"
    %% project_directory -->* virtual_environment.Venv : ".direnv/"
    %% venv *-- pip-tools
    %% venv *-- python_dependencies

    dot_envrc ..> direnv
    justfile ..> direnv
    justfile ..> pip-tools
    dot_envrc <.. pip-tools : "installed by"
    just <.. justfile
    requirements_txt ..> justfile : "generated from"