@startuml
' === Global look & feel =============


' === Global look & feel =============
skinparam defaultFontSize 20
' skinparam BackgroundColor #00000010
skinparam BackgroundColor transparent
allow_mixing 

' ======================================
skinparam package {
    RoundCorner 15
    BorderThickness 2
    BackgroundColor #00A2FF19
    BorderColor #00A2FF
    FontColor   #00A2FF
}
skinparam package<<Global Environment>><<Python Package>> {
    BackgroundColor #afb20019
    BorderColor #afb200ff
    FontColor   #afb200ff
}

' =======================================

skinparam rectangle {
  Shadowing false
  BorderColor none
  BackgroundColor #99999977
  RoundCorner 15
}

skinparam class {
    BackgroundColor #99999977
    BorderColor     #444444
    BorderThickness 1
    FontStyle bold
    RoundCorner 15
}


<style>
arrow {
    LineThickness 3
}
</style>



package """buildben""" as BB <<Python Package>> {
  ' rectangle "**""init-database""**" as BBdb <<Module>>
  ' rectangle "**""add-experiment""**" as BBexp <<Module>>
  ' rectangle "**""env-snapshot""**" as BBenvsnap <<Module>>
  rectangle "**Templates:**\n""• pyproject.toml""\n""• .envrc""\n""• justfile""\n""•"" ..." as TEMP
  rectangle "**""$ bube init-proj""**" as BBinitcli

}
<style>
arrow {
    FontStyle italic
    LineColor #afb200ff
    FontColor   #afb200ff
}
</style>

BBinitcli <-left- TEMP : copied by


package "Project" as P <<Directory & Environment>>{  

  rectangle "**Python Tools**: \n• ""pip-tools"" (compile/sync) \n• Virtual-environment\n• ..." as PyTools 
  rectangle "**Universal Tools**: \n• ""direnv""\n• ""just""\n• ..." as Tools 
}

rectangle "**Python Standards**: \n• PEP 405: Virtual-environment \n• PEP 621: ""pyproject.toml""\n• PEP 660: Editable install\n•  PEP 751: Lock-files\n•  PyPA: ""src/""-Layout" as Standards  #f27f72dc


<style>
arrow {
    LineColor #00A2FF
    LineThickness 2.5
    FontColor #00A2FF
    FontStyle italic
}
</style>

BBinitcli -[thickness=4]-> P : **creates project scaffold** (buildben is no dependency of project)

Tools -right-> PyTools : **automate** \n**& simplify**

<style>
arrow {
    LineStyle 10-5
    LineColor #EE220C
    FontColor #EE220C
}
</style>
PyTools --> Standards : **comply with**
TEMP --> Standards : **comply with**


@enduml
