#!/bin/bash
# ./<my_project>/experiments/<experiment_name_full>/.envrc
source_up # < pull in the root variables

# === Useful variables ================================================
# > Read them in your python script using os.getenv("VAR_NAME")
export EXP_NAME="$(basename "$PWD")"
export EXP_INPUT="$PWD/input"
export EXP_INTERM_OUTPUT="$PWD/interm-output"
export EXP_OUTPUT="$PWD/output"

# === Echo all env vars & info ======================================
echo
echo "=== Experiment-Related Environment Variables ==="
echo "EXP_NAME: $EXP_NAME"
echo "EXP_INPUT: $EXP_INPUT"
echo "EXP_INTERM_OUTPUT: $EXP_INTERM_OUTPUT"
echo "EXP_OUTPUT: $EXP_OUTPUT"
echo
